/// <reference types="vite/client" />
import { GoogleGenAI } from "@google/genai";

// Dynamic init right before API call
export function getAiClient() {
  let rawKey: any = undefined;

  // 1. Try localStorage first
  if (typeof window !== 'undefined' && window.localStorage) {
    rawKey = localStorage.getItem("gemini_api_key");
  }

  // 2. Try process.env
  if (!rawKey && typeof process !== 'undefined' && process.env) {
    rawKey = process.env.API_KEY || process.env.GEMINI_API_KEY;
  }
  
  // 3. Try import.meta.env (Vite)
  if (!rawKey && typeof import.meta !== 'undefined' && typeof import.meta.env !== 'undefined') {
    rawKey = import.meta.env.VITE_API_KEY || import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.VITE_OPENAI_API_KEY;
  }

  // 4. Convert to string safely
  const apiKey = String(rawKey || "").trim();

  // 5. Validate
  if (!apiKey) {
    throw new Error("API key is missing. Please configure it in the API Settings tab.");
  } else if (!apiKey.startsWith("AIza") && !apiKey.startsWith("sk-")) {
    console.warn("API key might be invalid (does not start with 'AIza' or 'sk-').");
  }

  return new GoogleGenAI({ apiKey });
}

export async function testGeminiConnection(apiKeyToTest: string): Promise<boolean> {
  try {
    const key = String(apiKeyToTest || "").trim();
    if (!key) return false;
    
    const ai = new GoogleGenAI({ apiKey: key });
    // Make a lightweight call to verify the key
    await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: 'test'
    });
    return true;
  } catch (e) {
    console.error("Connection test failed:", e);
    return false;
  }
}

export type AspectRatio = "1:1" | "16:9" | "9:16" | "4:5" | "3:4" | "4:3" | "5:7" | "8.5:11" | "A4";
export type Quality = "512px" | "1K" | "2K" | "4K";
export type ImageStyle = "Realistic" | "Clipart" | "Cartoon" | "Sticker" | "Logo" | "Icon" | "3D Render";

export async function generateImageFromPrompt(
  prompt: string,
  negativePrompt: string,
  aspectRatio: string,
  quality: string,
  style?: string
): Promise<string> {
  const ai = getAiClient();
  
  // Format prompt based on style and negative prompt
  let finalPrompt = style ? `Style: ${style}. ${prompt}` : prompt;
  if (negativePrompt) {
    finalPrompt += `. Do not include: ${negativePrompt}`;
  }

  // Adjust aspect ratio mappings if needed, 3:4 or 4:5 
  // (Nano banana supports "1:1", "3:4", "4:3", "9:16", "16:9", "1:4", "1:8", "4:1", "8:1")
  let mappedAspectRatio = aspectRatio;
  if (aspectRatio === "4:5" || aspectRatio === "5:7" || aspectRatio === "8.5:11" || aspectRatio === "A4") {
    mappedAspectRatio = "3:4";
  }
  
  if (aspectRatio === "5:7") finalPrompt += " (Size: 5x7 inch Invitation portrait)";
  if (aspectRatio === "8.5:11") finalPrompt += " (Size: 8.5x11 inch US Letter portrait)";
  if (aspectRatio === "A4") finalPrompt += " (Size: A4 International portrait)";

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          { text: finalPrompt }
        ],
      },
      config: {
        // @ts-ignore - Ignore type error if imageConfig is missing from old types
        imageConfig: {
          aspectRatio: mappedAspectRatio,
          imageSize: quality
        }
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the AI.");
  } catch (e: any) {
    if (e.message?.includes("403") || e.message?.includes("PERMISSION_DENIED") || e.status === 403 || e.status === "PERMISSION_DENIED") {
      console.warn("Got 403 with gemini-3.1-flash-image-preview, falling back to gemini-2.5-flash-image");
      // Fallback to older model
      const fallbackResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            { text: finalPrompt }
          ],
        },
        config: {
          // @ts-ignore
          imageConfig: {
            aspectRatio: mappedAspectRatio,
            imageSize: quality
          }
        },
      });
      for (const part of fallbackResponse.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
      throw new Error("No image generated by the fallback AI model.");
    } else {
      throw e;
    }
  }
}

export async function editImageFromPrompt(
  prompt: string,
  base64Image: string,
  mimeType: string,
  aspectRatio: string,
  quality: string,
  style?: string
): Promise<string> {
  const ai = getAiClient();
  
  let finalPrompt = style ? `Style: ${style}. ${prompt}` : prompt;
  
  if (aspectRatio === "5:7") finalPrompt += " (Size: 5x7 inch Invitation portrait)";
  if (aspectRatio === "8.5:11") finalPrompt += " (Size: 8.5x11 inch US Letter portrait)";
  if (aspectRatio === "A4") finalPrompt += " (Size: A4 International portrait)";

  // Since we pass base64Image, it must be clean base64 data without data URL prefix
  const pureBase64 = base64Image.split(',')[1] || base64Image;

  try {
    const response = await ai.models.generateContent({
      // Editing tasks fall back to gemini-2.5-flash-image if 3.1 isn't working with images for edit
      model: 'gemini-3.1-flash-image-preview',
      contents: {
        parts: [
          {
            inlineData: {
              data: pureBase64,
              mimeType: mimeType,
            },
          },
          { text: finalPrompt },
        ],
      },
      config: {
        // @ts-ignore
        imageConfig: {
          aspectRatio: aspectRatio === "4:5" || aspectRatio === "5:7" || aspectRatio === "8.5:11" || aspectRatio === "A4" ? "3:4" : aspectRatio,
          imageSize: quality
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the AI.");
  } catch (e: any) {
    if (e.message?.includes("403") || e.message?.includes("PERMISSION_DENIED") || e.status === 403 || e.status === "PERMISSION_DENIED") {
      console.warn("Got 403 with gemini-3.1-flash-image-preview, falling back to gemini-2.5-flash-image");
      const fallbackResponse = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: pureBase64,
                mimeType: mimeType,
              },
            },
            { text: finalPrompt },
          ],
        },
        config: {
          // @ts-ignore
          imageConfig: {
            aspectRatio: aspectRatio === "4:5" || aspectRatio === "5:7" || aspectRatio === "8.5:11" || aspectRatio === "A4" ? "3:4" : aspectRatio,
            imageSize: quality
          }
        }
      });
      for (const part of fallbackResponse.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
      throw new Error("No image generated by the fallback AI model.");
    } else {
      throw e;
    }
  }
}

export async function describeImage(
  base64Image: string,
  mimeType: string
): Promise<string> {
  const ai = getAiClient();
  const pureBase64 = base64Image.split(',')[1] || base64Image;

  const prompt = "Describe this image in detail to create a high-quality prompt for an AI image generator. Focus on composition, colors, lightning, style, and specific subjects. Keep it descriptive but concise enough to be used as a prompt.";

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: pureBase64,
            mimeType: mimeType,
          },
        },
        { text: prompt },
      ],
    },
  });

  const text = response.text;
  if (!text) throw new Error("Could not extract description from image.");
  
  return text;
}
